iqlusioninc/yubihsm.rs

.github/workflows/rust.yml, Cargo.toml, README.md, src/client.rs, src/ecdh.rs, src/ecdh/commands.rs, src/rsa.rs, src/rsa/pkcs1.rs, src/rsa/pss.rs, src/ssh.rs, src/ssh/commands.rs
There's not a cryptographic risk in these APIs per se: they simply won't work if they haven't been implemented correctly.
=> Rename `yolocrypto` feature to `untested`

src/connector/usb/connection.rs, src/connector/usb/device.rs
This fixes a bug in device enumeration and reconnection on some
libusb backends (detected on macOS, but possibly present on others);
using `GlobalContext` caused the list of devices returned by `devices()`
to not be updated, while creating a new `Context` for each list
operation ensures that the list is always fresh.
This changeset removes the current panic behavior --
`GlobalContext::default().devices()` contains an explicit `panic!`
when it can't initialize its backing `libusb_context*`, while
`Context::new()` gets unwrapped and error-handled via
`impl From<rusb::Error> for Error`.
Closes #14.
=> connector/usb: Use rusb::Context instead of GlobalContext

Cargo.lock, Cargo.toml
- `aes` => v0.5
- `block-modes` => v0.6
- `cmac` => v0.4
- `hmac` => v0.9
- `pbkdf2` => v0.5
=> Bump RustCrypto dependencies

.github/workflows/security_audit.yml, Cargo.lock
Unfortunately we can't pass an `--ignore` option to cargo-audit via `actions-rs/audit-check` to ignore the request smuggling vulnerability in `tiny_http` due to this issue:
https://github.com/actions-rs/audit-check/issues/132
This PR switches to invoking `cargo audit` directly so we can.
=> Replace `actions-rs/audit-check` with direct `cargo audit` invocation

src/ecdsa/signer.rs, tests/ecdsa/mod.rs
Support for creating Ethereum-style recoverable ECDSA/secp256k1 signatures.
=> Add support for k256::ecdsa::recoverable::Signature

Cargo.lock, src/mockhsm/object/payload.rs
Uses a method that strips the tag byte
=> Use `elliptic_curve::EncodedPoint::to_untagged_bytes()`

src/authentication/credentials.rs, src/authentication/key.rs, src/client.rs, src/connector.rs, src/connector/http/config.rs, src/connector/usb/config.rs, src/ecdsa.rs, src/lib.rs
Documents which cargo features must be enabled to use different parts of the API.
=> Add more `doc_cfg`

.cargo/audit.toml, .github/workflows/security_audit.yml, Cargo.lock, Cargo.toml
Bumps `rusb` to v0.7, will manually test yubihsm.
=> Update dependencies & add .cargo/audit.toml

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/asymmetric/public_key.rs, src/client.rs, src/ecdsa.rs, src/ecdsa/signer.rs, src/mockhsm/command.rs, src/mockhsm/object/objects.rs, src/mockhsm/object/payload.rs, src/object/label.rs, src/response/code.rs, src/response/message.rs, src/serialization.rs, src/session.rs, src/session/securechannel.rs, src/session/securechannel/kdf.rs, tests/command/sign_ecdsa.rs, tests/ecdsa/mod.rs
Updates the following:
- `aead` v0.4
- `aes` v0.7
- `bitvec` v0.20
- `block-modes` v0.8
- `ccm` v0.4
- `cipher` v0.3
- `cmac` v0.6
- `const-oid` v0.5
- `crypto-mac` v0.11
- `der` v0.3
- `ecdsa` v0.11
- `elliptic-curve` v0.9
- `ff` v0.9
- `group` v0.9
- `hmac` v0.11
- `k256` v0.8
- `p256` v0.8
- `p384` v0.7
- `pbkdf2` v0.8
- `pkcs8` v0.6
- `rand_core` v0.6
=> RustCrypto dependency updates; MSRV 1.49+

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, src/asymmetric/public_key.rs, src/client.rs, src/connector/usb/device.rs, src/lib.rs, src/mockhsm/command.rs, src/otp/commands/put.rs, src/response/code.rs
Bumps the following dependencies:
- `ecdsa` v0.12
- `k256` v0.9
- `p256` v0.9
- `p384` v0.8
=> Bump `k256`, `p256`, `p384`, `ecdsa`; MSRV 1.51+

Cargo.lock, Cargo.toml, src/connector/error.rs, src/connector/http.rs, src/connector/http/client.rs, src/connector/http/client/connection.rs, src/connector/http/client/error.rs, src/connector/http/client/path.rs, src/connector/http/client/request.rs, src/connector/http/client/response.rs, src/connector/http/client/response/body.rs, src/connector/http/client/response/reader.rs, src/connector/http/connection.rs
The `harp` crate provided a minimalist HTTP client that does what the YubiHSM connector client needs, and nothing more.
yubihsm.rs is currently the only user of `harp`, so it makes sense to just vendor it into this crate so it doesn't need to be maintained separately and refactoring can apply to both. (As it were, `harp` was extracted from this crate with the goals of making it more general, but that never worked out. C'est la vie)
Long term it would probably make sense to switch to a minimalist HTTP client like `ureq`.
=> Vendor HTTP client from `harp`

Cargo.lock, Cargo.toml, src/setup/report.rs
The `time` crate provides all of the features we need and is more actively maintained.
=> Replace `chrono` with the `time` crate

Cargo.lock, Cargo.toml, tests/integration.rs
`once_cell` avoids the use of macros, and will hopefully eventually be merged into the standard library.
=> Replace `lazy_static` with `once_cell`

src/client.rs
Context: iqlusioninc/tmkms#37
To summarize, the `yubihsm::Client` type has internal locking for a `Session` with the YubiHSM. There is actually very little lock-related code associated with this scheme, but there appears to be a subtle reentrancy bug in pretty much the only function where it could possibly exist: the `yubihsm::Client::send_command` method.
Based on discussions on iqlusioninc/tmkms#37 the bug definitely seemed to be tied to rekeying the session after a preset number of messages had been sent. It appears there was a reentrancy bug where an RAII guard was still holding the `Mutex` for the session state, which prevented a subsequent attempt to resent the message from acquiring it.
The solution is to explicitly drop the stale session guard prior to trying to establish a new …
=> Attempted bugfix for potential session reentrancy bug

Cargo.lock, Cargo.toml, README.md, src/client.rs, src/connector/http/client/connection.rs, src/rsa/oaep.rs, src/rsa/oaep/commands.rs, src/rsa/oaep/decrypted_data.rs, tests/command/decrypt_oaep.rs, tests/command/generate_asymmetric_key.rs, tests/command/mod.rs
Hi, I've been working with yubihsm2 in in Rust, and had to use the `decrypt_oaep` command, so I decided to make a contribution.
I've tested the code on a live device, and it seems to work fine. Hopefully the patch makes sense to you as well.
There are two points I'd like to additionally discuss (and potentially change during in this PR):
- I changed the default connection timeout (5 s -> 20 s) because RSA key generation takes quite some time. I could revert this and construct such a client specific to these tests, but it made sense to me to have default values that tolerate this command.
- I was thinking of making `decrypt_oaep` in `Client` a bit more "high level" by taking the OAEP label as a parameter, and make the function responsible for properly computing its hash and passing it on …
=> Add suport for decrypt_oaep command

Cargo.lock, Cargo.toml, src/asymmetric/public_key.rs, src/connector/usb/config.rs, src/ecdsa/signer.rs, src/mockhsm/command.rs, src/mockhsm/object/payload.rs, tests/ecdsa/mod.rs
Updates the RustCrypto elliptic curve crates to the following releases:
- `ecdsa` v0.13
- `k256` v0.10
- `p256` v0.10
- `p384` v0.9
=> Bump `elliptic-curve` crates to v0.11-based releases

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, src/ecdsa/signer.rs, src/mockhsm/command.rs, src/mockhsm/digest.rs, tests/ecdsa/mod.rs
Bump asymmetric crypto dependencies from Rust Crypto.
This is prompted by the conflict below in [ethers-rs](https://github.com/gakonst/ethers-rs) after the following change:
```diff
diff --git a/ethers-core/Cargo.toml b/ethers-core/Cargo.toml
index 00fa752..11d4a2c 100644
--- a/ethers-core/Cargo.toml
+++ b/ethers-core/Cargo.toml
@@ -18,7 +18,7 @@ rlp-derive = { version = "0.1.0", default-features = false }
-k256 = { version = "0.10.4", default-features = false, features = ["keccak256", "ecdsa", "std"] }
+k256 = { version = "0.11.2", default-features = false, features = ["keccak256", "ecdsa", "std"] }
```
Conflict:
```
error: failed to select a version for `signature`.
... required by package `ecdsa v0.13.3`
... which satisfies dependency `ecdsa = "^0.13"` of package `yubihsm v0.40.0`
... …
```
=> Bump asymmetric crypto dependencies

Cargo.lock, Cargo.toml, src/command/message.rs, src/mockhsm/object/objects.rs, src/response/message.rs, src/session/message.rs, src/session/securechannel.rs, src/session/securechannel/kdf.rs, src/session/securechannel/mac.rs
Updates the following to use the latest RustCrypto symmetric crate releases:
- `aes` v0.8
- `ccm` v0.5
- `cmac` v0.7
- `cbc` v0.1 (replacing `block-modes`)
=> Update symmetric dependencies

Cargo.toml, src/ecdsa/signer.rs
Support for signing raw digests via a trait-based abstraction
=> Impl `signature::hazmat::PrehashSigner` for ECDSA signer

src/ecdsa/signer.rs, tests/ecdsa/mod.rs
Provides a common API for obtaining public key for the signer
=> Impl `signature::Keypair` trait for ECDSA signer

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/asymmetric/public_key.rs, src/authentication/algorithm.rs, src/authentication/key.rs, src/client.rs, src/ecdsa/secp256k1.rs, src/ecdsa/signer.rs, src/mockhsm/command.rs, src/mockhsm/object/payload.rs, tests/command/decrypt_oaep.rs, tests/command/sign_eddsa.rs, tests/ecdsa/mod.rs, tests/ed25519/mod.rs
Bumps the following dependencies to the latest versions:
- `ecdsa` v0.16
- `ed25519` v2
- `ed25519-dalek` v2.0.0-pre.0
- `k256` v0.13
- `p256` v0.13
- `p384` v0.13
- `pbkdf2` v0.12
- `rsa` v0.9.0-pre.0
- `signature` v2
=> Bump asymmetric crypto dependencies; MSRV 1.65

src/ecdsa/secp256k1.rs, src/ecdsa/signer.rs, tests/ecdsa/mod.rs
Implement recoverable signatures for ECDSA-Secp256k1 signer and make `PrehashSigner<Signature<Secp256k1>>` return normalized `s` values.
No recoverable [`signature::Signer`](https://docs.rs/signature/latest/signature/trait.Signer.html) implementation for [`yubihsm::ecdsa::Signer`](https://docs.rs/yubihsm/latest/yubihsm/ecdsa/struct.Signer.html) since we can't implement [`signature::PrehashSignature`](https://docs.rs/signature/latest/signature/trait.PrehashSignature.html) for `(Signature<Secp256k1>, RecoveryId)`.
There is a bit of a repetition now with the `P-256` and `P-384` implementations -- I could add a macro for them.
Related: https://github.com/gakonst/ethers-rs/issues/2158, https://github.com/gakonst/ethers-rs/pull/2260
=> Implement recoverable signatures for ECDSA-Secp256k1

Cargo.lock, Cargo.toml
Release notes: https://github.com/RustCrypto/RSA/pull/318
=> Bump `rsa` crate dependency to v0.9

src/audit/commands/get_log_entries.rs, src/command/code.rs
When command audit is enabled at HSM initialization, an "invalid" entry is present which would fail the deserialization and leave empty entries. Because the entries are left empty, the log-index can't be bumped.
This adds support for deserialization of those entries.
=> audit: Adds support for HSM initialization entry

src/connector/http/client/response/reader.rs
When yubihsm-connector is restarted / shutdown the yubihsm.rs http client enters infinite condition, and busy loops, eating up 100% of CPU time.
Components: TMKMS (v0.12.2) and yubihsm-connector (2021-03-ubuntu1804-amd64) + osmosis testnet node (can be any other cosmos-sdk network)
In this setup it's hard to reproduce. I am not sure why, but out of many tries, I managed to break tmkms/yubihsm.rs only once.
In this setup I can reproduce the issue every single time.
1. Start TMKMS + Osmosis node and observe tmkms logs to see signed votes
2. Restart yubihsm-connector (or shut it down and start again, or don't start at all)
3. Observe TMKMS logs, see the last log line:
```
Jun 28 18:32:47 <host A> tmkms[1349138]: 2023-06-28T18:32:47.623775Z DEBUG yubihsm::session: session=5 n=1147 …
```
=> handle closed yubihsm-connector connection

Cargo.lock, Cargo.toml, src/mockhsm/error.rs, src/mockhsm/object.rs, src/mockhsm/object/objects.rs, src/wrap.rs, src/wrap/info.rs, src/wrap/key.rs, src/wrap/message.rs, src/wrap/nonce.rs, tests/command/export_wrapped.rs
This also provides for deserialization of asymmetric private keys.
=> wrap: implement encryption/decryption of messages

src/client.rs
```
warning: unresolved link to `ecdsa::Signer`
--> src/client.rs:975:34
|
975 |     /// We recommend using the [`ecdsa::Signer`] type instead, which provides a
|                                  ^^^^^^^^^^^^^ no item named `Signer` in module `ecdsa`
|
= note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
```
=> fixup warning in documentation of `Client`

.cargo/audit.toml
It's not actionable until a new release of the `rsa` crate is available
=> .cargo/audit.toml: ignore RUSTSEC-2023-0071

Cargo.lock, Cargo.toml, src/authentication/key.rs, src/ecdsa/signer.rs, tests/ecdsa/mod.rs
this allows users to use the `ecdsa::Signer` to build x509, CSR or other objects.
=> ecdsa: provide der-encoded signatures

src/algorithm.rs, src/ecdsa/signer.rs
Rustc 1.78 introduced new `unnecessary qualification` warnings.
=> fixups for rust-1.78

.github/workflows/ci.yml, tests/test_vectors/mod.rs
The tests were running with ambiant version of rust. GitHub just updated the rust version to 1.79
https://github.com/actions/runner-images/blob/ubuntu22/20240616.1/images/ubuntu/Ubuntu2204-Readme.md
=> ci: run ci with specified versions of rust

Cargo.lock, src/connector/usb/device.rs
Updates the following dependencies:
$ cargo update
Updating crates.io index
Locking 40 packages to latest compatible versions
Updating aes v0.8.3 -> v0.8.4
Updating autocfg v1.1.0 -> v1.3.0
Updating bitflags v2.4.2 -> v2.6.0
Updating cc v1.0.83 -> v1.0.101
Updating chunked_transfer v1.4.1 -> v1.5.0
Updating const-oid v0.9.5 -> v0.9.6
Updating cpufeatures v0.2.11 -> v0.2.12
Updating curve25519-dalek v4.1.1 -> v4.1.3
Updating der v0.7.8 -> v0.7.9
Updating deranged v0.3.9 -> v0.3.11
Updating fiat-crypto v0.2.5 -> v0.2.9
Updating flagset v0.4.4 -> v0.4.5
Updating getrandom v0.2.11 -> v0.2.15
Updating itoa v1.0.9 -> v1.0.11
Updating lazy_static v1.4.0 -> v1.5.0
Updating libc v0.2.150 -> v0.2.155
Updating libusb1-sys v0.6.4 -> v0.7.0
Updating log v0.4.20 -> v0.4.21
Updating num-integer v0.1.45 …
=> Cargo.lock: bump dependencies

src/rsa/oaep/commands.rs
label_data was always empty because it was consumed by data.
This commits re-splits the payload according to the selected mgf hash.
=> oaep: fixup `Deserialize` implementation

src/ecdsa/signer.rs
The length of prehashed content expected for p384 was incorrect.
=> ecdsa: fixup p384 support

Cargo.lock, Cargo.toml
rusb introduced an API break between 0.9.3 and 0.9.4.
https://github.com/a1ien/rusb/compare/v0.9.3-rusb..v0.9.4-rusb#diff-d5edd151ab03396da2ef0f89796c9fc95e3bec5e1a6a7a3ac5e46ead5e676a4dL225
=> rusb: mitigate API break

src/serialization.rs
The implementation of array deserializer expects the payload to be serialized as array. Sadly the serializer left the door open for the underlying serializer to choice either bytes or array, if available.
This would only occur when the objects are used outside yubihsm.rs.
This change was tested on both mockhsm and yubihsm on usb.
=> serializer: force serialization as array

src/error.rs
This fixes CI for rust 1.80.
This effectively adds support for backtrace which came in rust 1.65 (MSRV is currently 1.70).
=> rust 1.80 ci fixes

src/session.rs
When a slow operation is running on the HSM (like a RSA key generation >= 3072), the HSM will be busy for more than the session timeout of 30seconds.
Although the device did not reply within timeout, it did not discard the session, and we should not either. This bumps the last_active when we receive a reply from the HSM.
=> session: avoid unnecessary timeouts

src/asymmetric/public_key.rs
`<C as Curve>::Uint` represents the field elements, not their serialized size. This what `<C as Curve>::FieldBytesSize` is intended to be.
This is consistent for all the curves implemented here, but this breaks the deserialization of NistP521 curve points.
=> ecdsa: fixup public key deserialization for ecc

Cargo.lock, Cargo.toml, src/audit/commands/get_log_entries.rs
When serializing response codes, in the case of an error, the payload would be serialized differently than what the device gives us.
In the case of a soft error, the response code should be serialized from the bottom up, and not from the midpoint like it was.
This was breaking the hash computation.
This introduces a new type for the purpose of audit log which represent the correct behavior. That fixes two cases I've observed: the log in the case of a reboot and the error in case an object would not exist.
=> audit: fixup log entry serialization

src/mockhsm/object/payload.rs, tests/rsa/mod.rs
This fixes the implementation made in #510 
Tested against the mockhsm and a real device on USB.
=> mockhsm(rsa): when wrapped, the modulus is appended to the message
